# Generated by Django 5.1.1 on 2024-11-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StackTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desarrollo_web', models.TextField()),
                ('desarrollo_software', models.TextField()),
                ('base_datos', models.TextField()),
                ('otros', models.TextField()),
            ],
        ),
    ]
